version: 0.0.{build}
environment:
  access_token:
    secure: VoTH2ml/pRgjLSGhfPO+NZfCoFzFcfrQjEIl/5+0UufeW6mEvccfwvef3gOaD2ke
image:
  - Visual Studio 2022
  - macOS
  - Ubuntu
skip_commits:
  files:
    - docs/*
  message: /\[nobuild\]/
skip_tags: true
pull_requests:
  do_not_increment_build_number: true
configuration:
  - Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: 'OpenUtau\OpenUtau.csproj'
  version: "{version}"
before_build:
  - cmd: git config --global credential.helper store
  - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
  - cmd: git config --global user.email "appveyor@appveyor.com"
  - cmd: git config --global user.name "appveyor"
  - cmd: nuget restore
after_build:
  - cmd: python appveyor.py
artifacts:
  - path: bin\win-x86
    name: OpenUtau-win-x86
    type: zip
  - path: bin\win-x64
    name: OpenUtau-win-x64
    type: zip
  - path: OpenUtau-osx-x64.dmg
  - path: OpenUtau-linux-x64.tar.gz
  - path: appcast.win-x86.xml
  - path: appcast.win-x64.xml
  - path: appcast.linux-x64.xml
  - path: appcast.osx-x64.xml
  - path: changelog.txt
for:
-
  matrix:
    only:
      - image: macOS
  build_script:
    - python appveyor.py
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
    - python appveyor.py
-
  branches:
    only:
      - master
  configuration: Release
  deploy:
    tag: build/$(APPVEYOR_BUILD_VERSION)
    release: v$(APPVEYOR_BUILD_VERSION)
    description: v$(APPVEYOR_BUILD_VERSION) $(APPVEYOR_REPO_COMMIT_TIMESTAMP)
    provider: GitHub
    auth_token:
      secure: VoTH2ml/pRgjLSGhfPO+NZfCoFzFcfrQjEIl/5+0UufeW6mEvccfwvef3gOaD2ke
    draft: false
    prerelease: false
    force_update: true
    on:
      branch: master
      APPVEYOR_REPO_TAG: false
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:discord_webhook
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:discord_webhook
